import assert from "node:assert/strict";
import { createHash, randomBytes, webcrypto } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  COMPANY_ENCRYPTION_SUITE,
  buildAgentDeviceRegistrationRecord,
  calculateKeyFingerprint,
  canonicalJson,
  createAgentEncryptionDevice,
  decryptFileFromCompanyContainer,
  encryptFileToCompanyContainer,
  hpkeOpen,
  hpkeSeal,
  unlockRememberedAgentEncryptionDevice,
  wrapAndRememberAgentEncryptionDevice,
} from "../scripts/trelio-company-encryption.mjs";

test("agent device fingerprint uses the backend JWK canonical form", async () => {
  const device = await createAgentEncryptionDevice();

  assert.equal(Object.hasOwn(device.publicEncryptionJwk, "key_ops"), false);
  assert.equal(Object.hasOwn(device.publicSigningJwk, "key_ops"), false);
  assert.equal(calculateKeyFingerprint({
    publicEncryptionJwk: { ...device.publicEncryptionJwk, key_ops: [], alg: "ECDH-ES" },
    publicSigningJwk: { ...device.publicSigningJwk, key_ops: ["verify"], alg: "ES256" },
  }), device.fingerprint);

  const registrationRecord = buildAgentDeviceRegistrationRecord({
    companyId: "11111111-1111-4111-8111-111111111111",
    userId: "22222222-2222-4222-8222-222222222222",
    fingerprint: device.fingerprint,
    publicEncryptionJwk: { ...device.publicEncryptionJwk, key_ops: [] },
    publicSigningJwk: { ...device.publicSigningJwk, key_ops: ["verify"] },
  });
  assert.deepEqual(registrationRecord.publicEncryptionJwk, device.publicEncryptionJwk);
  assert.deepEqual(registrationRecord.publicSigningJwk, device.publicSigningJwk);
});

test("agent device survives trusted local wrapping without retaining the phrase", async () => {
  const device = await createAgentEncryptionDevice();
  const wrapped = await wrapAndRememberAgentEncryptionDevice({
    device,
    encryptionSecret: "correct horse battery staple",
    companyId: "11111111-1111-4111-8111-111111111111",
  });

  assert.equal(JSON.stringify(wrapped).includes("correct horse battery staple"), false);
  const unlocked = await unlockRememberedAgentEncryptionDevice({
    record: wrapped.record,
    trustedUnlockKey: wrapped.trustedUnlockKey,
  });
  assert.equal(unlocked.fingerprint, device.fingerprint);
});

test("agent device created by plugin 1.14.2 keeps its key pair and adopts the protocol fingerprint", async () => {
  const device = await createAgentEncryptionDevice();
  const legacyPublicEncryptionJwk = { ...device.publicEncryptionJwk, key_ops: [] };
  const legacyPublicSigningJwk = { ...device.publicSigningJwk, key_ops: ["verify"] };
  const legacyFingerprint = createHash("sha256")
    .update(canonicalJson({
      suite: COMPANY_ENCRYPTION_SUITE,
      publicEncryptionJwk: legacyPublicEncryptionJwk,
      publicSigningJwk: legacyPublicSigningJwk,
    }))
    .digest("base64url");
  assert.notEqual(legacyFingerprint, device.fingerprint);

  const wrapped = await wrapAndRememberAgentEncryptionDevice({
    device: {
      ...device,
      publicEncryptionJwk: legacyPublicEncryptionJwk,
      publicSigningJwk: legacyPublicSigningJwk,
      fingerprint: legacyFingerprint,
    },
    encryptionSecret: "correct horse battery staple",
    companyId: "11111111-1111-4111-8111-111111111111",
  });
  const unlocked = await unlockRememberedAgentEncryptionDevice({
    record: wrapped.record,
    trustedUnlockKey: wrapped.trustedUnlockKey,
  });

  assert.equal(wrapped.record.fingerprint, legacyFingerprint);
  assert.equal(unlocked.fingerprint, device.fingerprint);
  assert.deepEqual(unlocked.publicEncryptionJwk, device.publicEncryptionJwk);
  assert.deepEqual(unlocked.publicSigningJwk, device.publicSigningJwk);
});

test("dependency-free RFC 9180 implementation seals and opens P-256 envelopes", async () => {
  const recipient = await webcrypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" },
    true,
    ["deriveBits"],
  );
  const publicJwk = await webcrypto.subtle.exportKey("jwk", recipient.publicKey);
  const privateJwk = await webcrypto.subtle.exportKey("jwk", recipient.privateKey);
  const plaintext = randomBytes(97);
  const aad = { suite: COMPANY_ENCRYPTION_SUITE, purpose: "test-envelope", revision: 7 };
  const envelope = await hpkeSeal({
    recipientPublicEncryptionJwk: publicJwk,
    plaintext,
    aad,
  });
  const opened = await hpkeOpen({
    recipientPrivateKey: recipient.privateKey,
    recipientPrivateJwk: privateJwk,
    envelope,
    aad,
  });

  assert.deepEqual(opened, plaintext);
});

test("bridge opens an envelope produced by the browser @hpke/core implementation", async () => {
  // Static interoperability vector generated by @hpke/core 1.9.0. Keeping it
  // here catches a self-consistent but non-standard bridge implementation.
  const privateJwk = {
    key_ops: ["deriveBits"],
    ext: true,
    kty: "EC",
    x: "COYqQVPxkgh2O7v3m3l3AFDDQdLbyCPx4azyNjfVjto",
    y: "ksCZRYIFY6OuycKuR_279TnHpfLDedP49ma8SQyVQWM",
    crv: "P-256",
    d: "aWUIocuhJDsi-98Cffw7ABcWRMKwYK1YD0CqswXj7Vo",
  };
  const privateKey = await webcrypto.subtle.importKey(
    "jwk",
    privateJwk,
    { name: "ECDH", namedCurve: "P-256" },
    false,
    ["deriveBits"],
  );
  const opened = await hpkeOpen({
    recipientPrivateKey: privateKey,
    recipientPrivateJwk: privateJwk,
    envelope: {
      enc: "BKvHZKuNAJH9NfH-vmpxzSIojPidlddToOALKEiWqW_aeEPC-TRxobZzC6vTetSDmy_Lmem7v0YaLT-vbx23Zi8",
      ciphertext: "D-5KKIqYhJWBVLfaa1I9rkJRfZwcqasiCGTefLGhJWxKRDvc96mMaK_t",
    },
    aad: { purpose: "interop", revision: 3, suite: COMPANY_ENCRYPTION_SUITE },
  });

  assert.equal(opened.toString("utf8"), "Trelio HPKE interop vector");
});

test("bridge streams a browser-compatible multi-chunk TRELIOE1 file", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "trelio-e2ee-test-"));
  const sourcePath = path.join(directory, "source.bundle");
  const encryptedPath = path.join(directory, "encrypted.bin");
  const decryptedPath = path.join(directory, "decrypted.bundle");
  const scope = await webcrypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" },
    true,
    ["deriveBits"],
  );
  const publicJwk = await webcrypto.subtle.exportKey("jwk", scope.publicKey);
  const privateJwk = await webcrypto.subtle.exportKey("jwk", scope.privateKey);
  const bytes = randomBytes(4 * 1024 * 1024 + 37);

  try {
    await writeFile(sourcePath, bytes);
    const encrypted = await encryptFileToCompanyContainer({
      sourcePath,
      destinationPath: encryptedPath,
      scopePublicEncryptionJwk: publicJwk,
      aad: {
        companyId: "11111111-1111-4111-8111-111111111111",
        scopeId: "22222222-2222-4222-8222-222222222222",
        scopeEpoch: 1,
        entityType: "agent_workspace_revision",
        entityId: "33333333-3333-4333-8333-333333333333",
        entityRevision: 1,
        schemaVersion: 1,
      },
      originalName: "workspace.bundle",
      mimeType: "application/vnd.git.bundle",
    });
    const decrypted = await decryptFileFromCompanyContainer({
      sourcePath: encryptedPath,
      destinationPath: decryptedPath,
      scopePrivateKey: scope.privateKey,
      scopePrivateJwk: privateJwk,
      expectedCiphertextSha256: encrypted.ciphertextSha256,
    });

    assert.equal(decrypted.originalName, "workspace.bundle");
    assert.deepEqual(await readFile(decryptedPath), bytes);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});
